version: '1'
services:
  web:
    type: web
    dockerfile_path: Dockerfile
    env_vars:
      - key: DASHSCOPE_API_KEY
        sync: false
    build_command: ''
    start_command: ''
    health_check_path: /
